# syntax=docker/dockerfile:1

FROM node:24-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

FROM base AS pruner
RUN npm install --global turbo@2.10.12
COPY . .
RUN pnpm turbo prune server --docker

FROM base AS builder
COPY --from=pruner /app/out/json/ .
RUN pnpm install --frozen-lockfile
COPY --from=pruner /app/out/full/ .
RUN pnpm turbo run build --filter=server
RUN pnpm --filter=server deploy --prod --legacy /app/deploy/server

FROM node:24-alpine AS runner
ENV NODE_ENV="production"
ENV PORT="8080"
WORKDIR /app

COPY --from=builder --chown=node:node /app/deploy/server/ ./

USER node
EXPOSE 8080
CMD ["node", "dist/index.js"]
